### ISSUE TITLE
starcoder2

### ISSUE THREAD

**Issue by michabbb** [aj47/lm-studio-presets#2]
hi,

which preset would u use when using this llm ?

https://huggingface.co/second-state/StarCoder2-15B-GGUF

thanks for any help/tip/adivise!

thanks

**Comment by aj47** [comment]
i just uploaded [starcoder](https://github.com/aj47/lm-studio-presets/blob/main/starcoder.preset.json)
which should help.
note that this is a completion model so it doesn't work as a chat where you can ask questions, you give it text to complete.
also you need to stop it manually or limit the output tokens 
![image](https://github.com/aj47/lm-studio-presets/assets/8023513/b6a8dc75-1df2-4907-b07a-828d56672a6b)

**Comment by michabbb** [comment]
Thanks for pointing to that! I guess I used it as a chat and that's why I got confused about very strange answers 😄

**Comment by aj47** [comment]
@michabbb have you seen this coding LLM leaderboard? https://evalplus.github.io/leaderboard.html

i think there are much better coding llms than starcoder. is there a particular reason why startcoder might be better?

**Comment by michabbb** [comment]
nope... amazing!!! thanks 😱🙏
